#!/bin/bash
# /etc/init.d/startKiwiBot

### BEGIN INIT INFO
# Provides:          kiwiBot
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to start a kiwibot at init
# Description:       Script to start kiwibot at boot time
### END INIT INFO

# If you want a command to always run, put it here
# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo  "Starting kiwiBot"
#     run application you want to start
      source /opt/ros/kinetic/setup.bash
      source /home/kiwi/cumbia_rover/ros/catkin_ws/devel/setup.bash
      source /home/kiwi/cumbia_rover/config/local_env_vars.sh
      node /home/kiwi/cumbia_rover/ros/catkin_ws/src/local_client/src/socketio-server/index.js &
      roslaunch /home/kiwi/cumbia_rover/ros/catkin_ws/launch/cumbia_rover.launch
    ;;
  stop)
    echo "Stopping kiwiBot"
    # kill application you want to stop
    source /opt/ros/kinetic/setup.bash
    for i in $( rosnode list ); do
    rosnode kill $i;
    done
    killall roscore
    ;;
  *)
    echo "Usage: /etc/init.d/kiwiBot {start|stop}"
    exit 1
    ;;
esac

exit 0
