// Generated by gencpp from file video_mapping/GetMoreCameraStatusResponse.msg
// DO NOT EDIT!


#ifndef VIDEO_MAPPING_MESSAGE_GETMORECAMERASTATUSRESPONSE_H
#define VIDEO_MAPPING_MESSAGE_GETMORECAMERASTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace video_mapping
{
template <class ContainerAllocator>
struct GetMoreCameraStatusResponse_
{
  typedef GetMoreCameraStatusResponse_<ContainerAllocator> Type;

  GetMoreCameraStatusResponse_()
    : camera_status()  {
    }
  GetMoreCameraStatusResponse_(const ContainerAllocator& _alloc)
    : camera_status()  {
      camera_status.assign(std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > (_alloc));
  }



   typedef boost::array<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , 3>  _camera_status_type;
  _camera_status_type camera_status;





  typedef boost::shared_ptr< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetMoreCameraStatusResponse_

typedef ::video_mapping::GetMoreCameraStatusResponse_<std::allocator<void> > GetMoreCameraStatusResponse;

typedef boost::shared_ptr< ::video_mapping::GetMoreCameraStatusResponse > GetMoreCameraStatusResponsePtr;
typedef boost::shared_ptr< ::video_mapping::GetMoreCameraStatusResponse const> GetMoreCameraStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace video_mapping

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'video_mapping': ['/home/overcode/multicamera_stitching/adquisition_module/catkin_ws/src/video_mapping/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "086d9f0441c56e91ac64021d69c7ba0c";
  }

  static const char* value(const ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x086d9f0441c56e91ULL;
  static const uint64_t static_value2 = 0xac64021d69c7ba0cULL;
};

template<class ContainerAllocator>
struct DataType< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "video_mapping/GetMoreCameraStatusResponse";
  }

  static const char* value(const ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[3] camera_status\n"
"\n"
;
  }

  static const char* value(const ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMoreCameraStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::video_mapping::GetMoreCameraStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "camera_status[]" << std::endl;
    for (size_t i = 0; i < v.camera_status.size(); ++i)
    {
      s << indent << "  camera_status[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.camera_status[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIDEO_MAPPING_MESSAGE_GETMORECAMERASTATUSRESPONSE_H
