// Generated by gencpp from file video_mapping/GetMoreCameraStatus.msg
// DO NOT EDIT!


#ifndef VIDEO_MAPPING_MESSAGE_GETMORECAMERASTATUS_H
#define VIDEO_MAPPING_MESSAGE_GETMORECAMERASTATUS_H

#include <ros/service_traits.h>


#include <video_mapping/GetMoreCameraStatusRequest.h>
#include <video_mapping/GetMoreCameraStatusResponse.h>


namespace video_mapping
{

struct GetMoreCameraStatus
{

typedef GetMoreCameraStatusRequest Request;
typedef GetMoreCameraStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMoreCameraStatus
} // namespace video_mapping


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::video_mapping::GetMoreCameraStatus > {
  static const char* value()
  {
    return "086d9f0441c56e91ac64021d69c7ba0c";
  }

  static const char* value(const ::video_mapping::GetMoreCameraStatus&) { return value(); }
};

template<>
struct DataType< ::video_mapping::GetMoreCameraStatus > {
  static const char* value()
  {
    return "video_mapping/GetMoreCameraStatus";
  }

  static const char* value(const ::video_mapping::GetMoreCameraStatus&) { return value(); }
};


// service_traits::MD5Sum< ::video_mapping::GetMoreCameraStatusRequest> should match 
// service_traits::MD5Sum< ::video_mapping::GetMoreCameraStatus > 
template<>
struct MD5Sum< ::video_mapping::GetMoreCameraStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::video_mapping::GetMoreCameraStatus >::value();
  }
  static const char* value(const ::video_mapping::GetMoreCameraStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::video_mapping::GetMoreCameraStatusRequest> should match 
// service_traits::DataType< ::video_mapping::GetMoreCameraStatus > 
template<>
struct DataType< ::video_mapping::GetMoreCameraStatusRequest>
{
  static const char* value()
  {
    return DataType< ::video_mapping::GetMoreCameraStatus >::value();
  }
  static const char* value(const ::video_mapping::GetMoreCameraStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::video_mapping::GetMoreCameraStatusResponse> should match 
// service_traits::MD5Sum< ::video_mapping::GetMoreCameraStatus > 
template<>
struct MD5Sum< ::video_mapping::GetMoreCameraStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::video_mapping::GetMoreCameraStatus >::value();
  }
  static const char* value(const ::video_mapping::GetMoreCameraStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::video_mapping::GetMoreCameraStatusResponse> should match 
// service_traits::DataType< ::video_mapping::GetMoreCameraStatus > 
template<>
struct DataType< ::video_mapping::GetMoreCameraStatusResponse>
{
  static const char* value()
  {
    return DataType< ::video_mapping::GetMoreCameraStatus >::value();
  }
  static const char* value(const ::video_mapping::GetMoreCameraStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VIDEO_MAPPING_MESSAGE_GETMORECAMERASTATUS_H
