// Generated by gencpp from file video_mapping/Status.msg
// DO NOT EDIT!


#ifndef VIDEO_MAPPING_MESSAGE_STATUS_H
#define VIDEO_MAPPING_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace video_mapping
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    : resolution()
    , quality(0.0)  {
    }
  Status_(const ContainerAllocator& _alloc)
    : resolution(_alloc)
    , quality(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _resolution_type;
  _resolution_type resolution;

   typedef float _quality_type;
  _quality_type quality;





  typedef boost::shared_ptr< ::video_mapping::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::video_mapping::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::video_mapping::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::video_mapping::Status > StatusPtr;
typedef boost::shared_ptr< ::video_mapping::Status const> StatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::video_mapping::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::video_mapping::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace video_mapping

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'video_mapping': ['/home/overcode/multicamera_stitching/adquisition_module/catkin_ws/src/video_mapping/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::video_mapping::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::video_mapping::Status_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::video_mapping::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::video_mapping::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::video_mapping::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::video_mapping::Status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::video_mapping::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68de8bf5b6d9757586af8a4bdbc8a1a5";
  }

  static const char* value(const ::video_mapping::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68de8bf5b6d97575ULL;
  static const uint64_t static_value2 = 0x86af8a4bdbc8a1a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::video_mapping::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "video_mapping/Status";
  }

  static const char* value(const ::video_mapping::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::video_mapping::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string resolution\n"
"float32 quality\n"
;
  }

  static const char* value(const ::video_mapping::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::video_mapping::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.resolution);
      stream.next(m.quality);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::video_mapping::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::video_mapping::Status_<ContainerAllocator>& v)
  {
    s << indent << "resolution: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.resolution);
    s << indent << "quality: ";
    Printer<float>::stream(s, indent + "  ", v.quality);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIDEO_MAPPING_MESSAGE_STATUS_H
