(cl:defpackage video_mapping-srv
  (:use )
  (:export
   "GETMORECAMERASTATUS"
   "<GETMORECAMERASTATUS-REQUEST>"
   "GETMORECAMERASTATUS-REQUEST"
   "<GETMORECAMERASTATUS-RESPONSE>"
   "GETMORECAMERASTATUS-RESPONSE"
  ))

